baseURL: 'https://angad.me/'
languageCode: en-us
# This title is used as the website title (navbar and meta title)
title: Angad Behl
theme: PaperMod

params:
  title: Hi, I'm Angad!
  description: "I'm a student and an aspiring software developer who loves tinkering with all things technology, especially self-hosting and open-source software. I've been known online as slashtechno as well."
  showtoc: true
  ShowCodeCopyButtons: true
  # Home info mode
  # homeInfoParams:
  #   Title: "I am Angad!"
  #   Content: This is my website.
  env: production # Enables enhanced SEO
  analytics:
    goatcounter:
      Code: "sudo"
      Src: "/count.js"
  images: [logo.png]
  ShowFullTextinRSS: true # Show full text in RSS feed
  ShowRssButtonInSectionTermList: true # Show RSS button in section term list
  profileMode:
    enabled: true
    # title: "Hi! I'm Angad!"
    subtitle: "This is my portfolio/blog, whatever you want to call it. I'm a student and an aspiring software developer who loves tinkering with all things technology, especially self-hosting and open-source software."
    buttons:
      - name: Blog
        url: "/blog/"
      - name: About
        url: "/about/"
  socialIcons: # Show the respective social icon linked to the corresponding URL
    - name: github
      url: "https://github.com/slashtechno"
    - name: mastodon 
      url: "https://fosstodon.org/@slashtechno"
  cover:
    linkFullImages: false # Clicking a post's cover image opens the image in a new tab
  editPost:
    URL: "https://github.com/slashtechno/angad/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
  # Other settings
  ShowBreadcrumbs: true # Show the path to a page'
  ShowReadingTime: true # Show the page's reading time
  # ShowShareButtons: true # Show the share buttons
  ShowPostNavLinks: true # Show navigation links under a post
outputs:
    home:
        - HTML
        # - JSON
        # - RSS

menu:
  main:
  # Right to left
    - identifier: Sponsor
      name: Sponsor
      url: https://github.com/sponsors/slashtechno
      weight: 5
    - identifier: github
      name: Github
      url: https://github.com/slashtechno
      weight: 4
    - identifier: fiverr
      name: Fiverr
      url: https://www.fiverr.com/angadbehl
      weight: 3
    - identifier: about
      name: About
      url: about/
      weight: 2
    - identifier: search
      name: Search
      url: search/
      weight: 1
taxonomies:
  tag: tags
  category: categories
  # series: series

enableGitInfo: true

# https://gohugo.io/getting-started/configuration/#configure-dates
frontmatter:
  date:
  - date
  - publishdate
  - pubdate
  - published
  # - lastmod
  # - modified
  expiryDate:
  - expirydate
  - unpublishdate
  lastmod:
  - lastmod
  - :git
  - :fileModTime
  publishDate:
  - publishdate
  - pubdate
  - published
  - date