baseURL: 'https://angad.me/'
languageCode: en-us
# This title is used as the website title (navbar and meta title)
title: Angad
theme: PaperMod

params:
  title: Hi! I'm Angad
  description: "I'm a student and an aspiring software developer who loves tinkering with all things technology, especially self-hosting and open-source software. I've been known online as slashtechno as well."
  # Home info mode
  # homeInfoParams:
  #   Title: "I am Angad!"
  #   Content: This is my website.
  env: production # Enables enhanced SEO
  images: [logo.png]
  ShowFullTextinRSS: true # Show full text in RSS feed
  ShowRssButtonInSectionTermList: true # Show RSS button in section term list
  profileMode:
    enabled: true
    # title: "Hi! I'm Angad!"
    subtitle: "This is my portfolio/blog, whatever you want to call it. I'm a student and an aspiring software developer who loves tinkering with all things technology, especially self-hosting and open-source software."
    buttons:
      - name: Blog Posts
        url: "/blog/"
      - name: Who am I?
        url: "/about/"
  socialIcons: # Show the respective social icon linked to the corresponding URL
    - name: github
      url: "https://github.com/slashtechno"
    - name: mastodon 
      url: "https://fosstodon.org/@slashtechno"
  cover:
    linkFullImages: true # Clicking a post's cover image opens the image in a new tab
  # Other settings
  ShowBreadcrumbs: true # Show the path to a page'
  ShowReadingTime: true # Show the page's reading time
  # ShowShareButtons: true # Show the share buttons
  # ShowPostNavLinks: true # Show navigation links under a post
outputs:
    home:
        - HTML
        # - JSON
        # - RSS

menu:
  main:
    - indentifier: github
      name: Github
      url: https://github.com/slashtechno
      weight: 2
    - indentifier: search
      name: Search
      url: search/
      weight: 1
